export enum MODEL{
    TREE = "/assets/models/tree.glb",
    ROCK = "/assets/models/rocks.glb",
    GROUND = "/assets/models/coast_ground.glb",
    BACKGROUND = "/assets/models/background.glb",
    BRIDGE = "/assets/models/bridge.glb",
    TELEVISION = "/assets/models/tv.glb",
    PLANTBOX="/assets/models/plantBox.glb",
    METALCAN="/assets/models/metalCan.glb",
    RADIO="/assets/models/radio.glb",
    MARVELFACE="/assets/models/marble_face.glb",
    LATERAL="/assets/models/lateral.glb",
    TOWER="/assets/models/tower.glb",
    BOAT="/assets/models/boat.glb",
    FISHINGBOAT="/assets/models/fishingBoat.glb",
    SNOWMOUNTAIN="/assets/models/snowMountain.glb",
    LANTERN="/assets/models/lantern.glb",
    CASSETTE="/assets/models/cassette_player.glb",
}